---
output: 
  pdf_document:
    includes:
      in_header: "Report.preamble.tex"
params: 
    sidebar_options: NULL
    surveyTable: NULL
    surveyTableValidator: NULL
    nvcAssignment: NULL
    floristicTables: NULL
    speciesFreq: NULL
    avgEIVs: NULL
    diversityAnalysis: NULL
    mvaNationalRefResults: NULL
    mvaLocalRefRestrictedResults: NULL
    mvaLocalRefUnrestrictedResults: NULL
    reportAuthorName: NULL
bibliography: Report.refs.bib
link-citations: yes
editor_options: 
  markdown: 
    wrap: 72
title: \textbf{\textcolor{ceh.dark.blue}{pseudoMAVIS}}
subtitle: \textbf{\textcolor{ceh.dark.blue}{Report}}
# date: \textbf{\textcolor{ceh.dark.blue}{`r Sys.Date()`}}
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(kableExtra)
```

```{r retrieve_data, message=FALSE, warning=FALSE, include=FALSE}

# source("../create_constants.R", local = knitr::knit_global())
# sys.source("./create_constants.R", envir = knitr::knit_global())

# Retrieve report parameters
surveyTable <- params$surveyTable
surveyTableValidator <- params$surveyTableValidator
nvcAssignment <- params$nvcAssignment
sidebar_options <- params$sidebar_options
floristicTables <- params$floristicTables
speciesFreq <- params$speciesFreq
avgEIVs <- params$avgEIVs
diversityAnalysis <- params$diversityAnalysis
mvaNationalRefResults <- params$mvaNationalRefResults
mvaLocalRefRestrictedResults <- params$mvaLocalRefRestrictedResults
mvaLocalRefUnrestrictedResults <- params$mvaLocalRefUnrestrictedResults

# Report options
reportOptions <- sidebar_options$reportOptions
reportAuthorName <- params$reportAuthorName
reportProjectName <- sidebar_options$reportProjectName

# Data Structure
surveyTableStructure <- surveyTableValidator$surveyTableStructure

# NVC Assignment
nvcAssignmentSite <- nvcAssignment$nvcAssignmentSite
nvcAssignmentGroup <- nvcAssignment$nvcAssignmentGroup
nvcAssignmentQuadrat <- nvcAssignment$nvcAssignmentQuadrat

# EIVs
weightedMeanHEValuesSite <- avgEIVs$weightedMeanHEValuesSite
unweightedMeanHEValuesSite <- avgEIVs$unweightedMeanHEValuesSite
weightedMeanHEValuesGroup <- avgEIVs$weightedMeanHEValuesGroup
unweightedMeanHEValuesGroup <- avgEIVs$unweightedMeanHEValuesGroup
weightedMeanHEValuesQuadrat <- avgEIVs$weightedMeanHEValuesQuadrat
unweightedMeanHEValuesQuadrat <- avgEIVs$unweightedMeanHEValuesQuadrat

# Diversity
diversitySummary <- diversityAnalysis$diversitySummary
diversityIndices <- diversityAnalysis$diversityIndices
speciesRichnessSite <- diversityAnalysis$speciesRichnessSite
speciesRichnessGroup <- diversityAnalysis$speciesRichnessGroup
speciesRichnessQuadrat <- diversityAnalysis$speciesRichnessQuadrat

# MVA Local Reference, Restricted
mvaLocalRefRestricted_quadrats_survey <- mvaLocalRefRestrictedResults$surveyTable_dca_results_quadrats
mvaLocalRefRestricted_hulls_pquads <- mvaLocalRefRestrictedResults$selected_pquads_dca_results_quadrats_final_hull
mvaLocalRefRestricted_arrow_plot_data <- mvaLocalRefRestrictedResults$arrow_plot_data
mvaLocalRefRestricted_CCA_arrowData <- mvaLocalRefRestrictedResults$CCA_arrowData

# MVA Local Reference, Unrestricted
mvaLocalRefUnrestricted_quadrats_survey <- mvaLocalRefUnrestrictedResults$pquads_surveyTable_dca_results_quadrats_sample
mvaLocalRefUnrestricted_hulls_pquads <- mvaLocalRefUnrestrictedResults$pquads_surveyTable_dca_results_quadrats_hull
mvaLocalRefUnrestricted_arrow_plot_data <- mvaLocalRefUnrestrictedResults$arrow_plot_data

# MVA National Reference
mvaNationalRef_quadrats_survey <- mvaNationalRefResults$surveyTable_dca_results_quadrats
mvaNationalRef_hulls <- mvaNationalRefResults$selected_pquads_dca_results_quadrats_final_hull



# Report options. Load from create_constants.R!!!
reportOptions_options <- list(`NVC Assignment` = c("Site" = "nvcAssignmentResultsSite",
                                                   "Group" = "nvcAssignmentResultsGroup",
                                                   "Quadrat" = "nvcAssignmentResultsQuadrat"),
                              `Floristic Tables` = c("Site" = "composedFloristicTablesSite",
                                                     "Group" = "composedFloristicTablesGroup"),
                              `Species Frequency` = c("Species Frequency" = "speciesFrequencyTable"),
                              `EIVs (incl. Mean Hill-Ellenberg)` = c("Weighted, Site" = "weightedMeanHEValuesSite",
                                                                     "Unweighted, Site" = "unweightedMeanHEValuesSite",
                                                                     "Weighted, Group" = "weightedMeanHEValuesGroup",
                                                                     "Unweighted, Group" = "unweightedMeanHEValuesGroup",
                                                                     "Weighted, Quadrat" = "weightedMeanHEValuesQuadrat",
                                                                     "Unweighted, Quadrat" = "unweightedMeanHEValuesQuadrat"),
                              `Diversity` = c("Summary" = "diversitySummary",
                                              "Quadrat Indices" = "diversityIndices",
                                              "Richness, Site" = "speciesRichnessSite",
                                              "Richness, Group" = "speciesRichnessGroup",
                                              "Richness, Quadrat" = "speciesRichnessQuadrat"),
                              `MVA` = c("National" = "mvaNationalReference",
                                        "Local (restricted)" = "mvaLocalReferenceRestricted",
                                        "Local (unrestricted)" = "mvaLocalReferenceUnrestricted"),
                              `Survey Table` = c("Survey Table" = "surveyTable")
    )
```

\vspace{-15truemm}

```{r reportAuthorName, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

cat("**Name:** ", as.character(reportAuthorName), sep = "")

```

```{r reportProjectName, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

cat("**Project:** ", as.character(reportProjectName), sep = "")

```

```{r reportProjectDate, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

cat("**Date & Time:** ", as.character(format(Sys.time(), "%Y-%m-%d %H:%M:%S")), sep = "")

```

# Introduction
The Modular Analysis of Vegetation Information System (MAVIS) is a tool..

# Survey Data Structure

```{r surveyTableStructure, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

kableExtra::kbl(x = surveyTableStructure, format = "latex", booktabs = TRUE,
                longtable = TRUE, linesep = "",
                caption = "The number of quadrats by group and year present in the inputted survey data.") |>
  kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))

```

```{r nvcAssignmentTitle, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

reportOptions_nvcAssignment <- reportOptions_options$`NVC Assignment`

if(any(reportOptions_nvcAssignment %in% reportOptions)){
  
  cat("\\newpage")
  cat("# NVC Assignment")
  
}

```

```{r nvcAssignmentResultsSite, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("nvcAssignmentResultsSite" %in% reportOptions){
  
  cat("## NVC Assignment Site")

  kableExtra::kbl(x = nvcAssignmentSite, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "The top NVC communities fitted using the pseudo-quadrat method, for the site by year.") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r nvcAssignmentResultsGroup, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("nvcAssignmentResultsGroup" %in% reportOptions){
  
  cat("## NVC Assignment Group")

  kableExtra::kbl(x = nvcAssignmentGroup, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "The top NVC communities fitted using the pseudo-quadrat method, by group and year") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r nvcAssignmentResultsQuadrat, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("nvcAssignmentResultsQuadrat" %in% reportOptions){
  
  cat("## NVC Assignment Quadrat")

  kableExtra::kbl(x = nvcAssignmentQuadrat, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "The top NVC communities fitted using the pseudo-quadrat method, by quadrat, group, and year") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r floristicTablesTitle, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

reportOptions_floristicTables <- reportOptions_options$`Floristic Tables`

if(any(reportOptions_floristicTables %in% reportOptions)){
  
  cat("\\newpage")
  cat("# Floristic Tables")
  
}

```

```{r floristicTablesSite, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("composedFloristicTablesSite" %in% reportOptions){
  
  cat("## Composed Floristic Tables Site")
  
  for(id in unique(floristicTables$ID)){

    floristicTables_selected <- floristicTables |>
      dplyr::filter(ID == id) |>
      dplyr::select(-ID)
  
    kableExtra::kbl(x = floristicTables_selected, format = "latex", booktabs = TRUE,
                    longtable = TRUE, linesep = "",
                    caption = paste0("Composed Floristic Table (", as.character(id), ")")) |>
      kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position")) |>
      print()
    
  }
  
}

```

```{r floristicTablesGroup, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("composedFloristicTablesGroup" %in% reportOptions){
  
  cat("## Composed Floristic Tables Group")
  
  for(id in unique(floristicTables$ID)){

    floristicTables_selected <- floristicTables |>
      dplyr::filter(ID == id) |>
      dplyr::select(-ID)
  
    kableExtra::kbl(x = floristicTables_selected, format = "latex", booktabs = TRUE,
                    longtable = TRUE, linesep = "",
                    caption = paste0("Composed Floristic Table (", as.character(id), ")")) |>
      kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position")) |>
      print()
    
  }
  
}

```

```{r speciesFrequency, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("speciesFrequencyTable" %in% reportOptions){
  
  cat("\\newpage")
  cat("# Species Frequency")

  speciesFreqTable <- speciesFreq |>
    dplyr::mutate_all(~replace(., is.na(.), ""))
  
  kableExtra::kbl(x = speciesFreqTable, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "The frequency of occurence of each species across all quadrats by year.") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r eivTitle, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

reportOptions_eiv <- reportOptions_options$`EIVs (incl. Mean Hill-Ellenberg)`

if(any(reportOptions_eiv %in% reportOptions)){
  
  cat("\\newpage")
  cat("# Ecological Indicator Values")
  
}

```

```{r weightedMeanHEValuesSite, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("weightedMeanHEValuesSite" %in% reportOptions){
  
  cat("## Weighted Mean Hill-Ellenberg Values Site")
  
  kableExtra::kbl(x = weightedMeanHEValuesSite, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r unweightedMeanHEValuesSite, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("unweightedMeanHEValuesSite" %in% reportOptions){
  
  cat("## Unweighted Mean Hill-Ellenberg Values Site")
  
  kableExtra::kbl(x = unweightedMeanHEValuesSite, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r weightedMeanHEValuesGroup, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("weightedMeanHEValuesGroup" %in% reportOptions){
  
  cat("## Weighted Mean Hill-Ellenberg Values Group")
  
  kableExtra::kbl(x = weightedMeanHEValuesGroup, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r unweightedMeanHEValuesGroup, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("unweightedMeanHEValuesGroup" %in% reportOptions){
  
  cat("## Unweighted Mean Hill-Ellenberg Values Group")
  
  kableExtra::kbl(x = unweightedMeanHEValuesGroup, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r weightedMeanHEValuesQuadrat, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("weightedMeanHEValuesQuadrat" %in% reportOptions){
  
  cat("## Weighted Mean Hill-Ellenberg Values Quadrat")
  
  kableExtra::kbl(x = weightedMeanHEValuesQuadrat, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r unweightedMeanHEValuesQuadrat, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("unweightedMeanHEValuesQuadrat" %in% reportOptions){
  
  cat("## Unweighted Mean Hill-Ellenberg Values Quadrat")
  
  kableExtra::kbl(x = unweightedMeanHEValuesQuadrat, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r diversityTitle, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

reportOptions_diversity <- reportOptions_options$Diversity

if(any(reportOptions_diversity %in% reportOptions)){
  
  cat("\\newpage")
  cat("# Diversity")
  
}

```

```{r diversitySummary, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("diversitySummary" %in% reportOptions){
  
  cat("## Diversity Summary")
  
  kableExtra::kbl(x = diversitySummary, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r diversityIndices, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("diversityIndices" %in% reportOptions){
  
  cat("## Diversity Indices")
  
  kableExtra::kbl(x = diversityIndices, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"), full_width = FALSE)
  
}

```

```{r speciesRichnessSite, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("speciesRichnessSite" %in% reportOptions){
  
  cat("## Species Richness, Site")
  
  kableExtra::kbl(x = speciesRichnessSite, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r speciesRichnessGroup, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("speciesRichnessGroup" %in% reportOptions){
  
  cat("## Species Richness, Group")
  
  kableExtra::kbl(x = speciesRichnessGroup, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r speciesRichnessQuadrat, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("speciesRichnessQuadrat" %in% reportOptions){
  
  cat("## Species Richness, Quadrat")
  
  kableExtra::kbl(x = speciesRichnessQuadrat, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

```{r mvaTitle, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

reportOptions_mva <- reportOptions_options$MVA

if(any(reportOptions_mva %in% reportOptions)){
  
  cat("\\newpage")
  cat("# Multivariate Analysis")
  
}

```

```{r mvaNationalRefTitle, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.align = 'center', fig.cap='Multivariate analaysis plot, national reference.'}

if("mvaNationalReference" %in% reportOptions){
  
  # cat("\\newpage")
  cat("## National Reference")
  
}

```

```{r mvaNationalRef, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.align = 'center', fig.cap='Multivariate analaysis plot, national reference.'}

if("mvaNationalReference" %in% reportOptions){
  
  # cat("## National Reference")
  
  mvaNationalRefPlot <- ggplot2::ggplot() +
    ggplot2::geom_polygon(data = mvaNationalRef_hulls, alpha = 0.2,
                          mapping = ggplot2::aes(x = DCA1,
                                                 y = DCA2,
                                                 fill = NVC
                                                 )) +
    ggplot2::geom_point(data = mvaNationalRef_quadrats_survey,
                        mapping = ggplot2::aes(Year = Year,
                                               Group = Group,
                                               Quadrat = Quadrat,
                                               x = DCA1,
                                               y = DCA2)) +
    # ggplot2::geom_segment(data = CCA_arrowData,
    #                       color = 'black',
    #                       arrow = grid::arrow(),
    #                       mapping = ggplot2::aes(x = 0,
    #                                              y = 0,
    #                                              xend = CCA1,
    #                                              yend = CCA2,
    #                                              label = `Hill-Ellenberg`)) +
    # ggplot2::geom_text(data = CCA_arrowData,
    #                    color = 'black',
    #                    # position = ggplot2::position_dodge(width = 0.9),
    #                    size = 5,
    #                    mapping = ggplot2::aes(x = CCA1 * 1.075,
    #                                           y = CCA2 * 1.075,
    #                                           label = `Hill-Ellenberg`)) +
    ggplot2::theme_minimal()

  mvaNationalRefPlot
  
}

```

```{r mvaLocalRefRestrictedTitle, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.align = 'center', fig.cap='Multivariate analaysis plot, local reference, restricted.'}

if("mvaLocalReferenceRestricted" %in% reportOptions){
  
  cat("\\newpage")
  cat("## Local Reference, Restricted")
  
}

```

```{r mvaLocalRefRestricted, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.align = 'center', fig.cap='Multivariate analaysis plot, local reference, restricted.'}

if("mvaLocalReferenceRestricted" %in% reportOptions){
  
  # cat("## Local Reference, Restricted")
  
  mvaLocalRefRestrictedPlot <- ggplot2::ggplot() +
    ggplot2::geom_polygon(data = mvaLocalRefRestricted_hulls_pquads, alpha = 0.2,
                          mapping = ggplot2::aes(x = DCA1, 
                                                 y = DCA2, 
                                                 fill = NVC.Comm
                                                 )) +
    ggplot2::geom_point(data = mvaLocalRefRestricted_quadrats_survey,
                        mapping = ggplot2::aes(Year = Year,
                                               Group = Group,
                                               Quadrat = Quadrat,
                                               x = DCA1,
                                               y = DCA2)) +
    ggplot2::geom_segment(data = mvaLocalRefRestricted_CCA_arrowData,
                          color = 'black',
                          arrow = grid::arrow(),
                          mapping = ggplot2::aes(x = 0,
                                                 y = 0,
                                                 xend = CCA1,
                                                 yend = CCA2,
                                                 label = `Hill-Ellenberg`)) +
    ggplot2::geom_text(data = mvaLocalRefRestricted_CCA_arrowData,
                       color = 'black',
                       # position = ggplot2::position_dodge(width = 0.9),
                       size = 5,
                       mapping = ggplot2::aes(x = CCA1 * 1.075,
                                              y = CCA2 * 1.075,
                                              label = `Hill-Ellenberg`)) +
    ggplot2::theme_minimal()

  mvaLocalRefRestrictedPlot
  
}

```

```{r mvaLocalRefUnrestrictedTitle, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.align = 'center', fig.cap='Multivariate analaysis plot, local reference, unrestricted.'}

if("mvaLocalReferenceUnrestricted" %in% reportOptions){
  
  cat("\\newpage")
  cat("## Local Reference, Unrestricted")
  
}

```

```{r mvaLocalRefUnrestricted, echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.align = 'center', fig.cap='Multivariate analaysis plot, local reference, unrestricted.'}

if("mvaLocalReferenceUnrestricted" %in% reportOptions){
  
  # cat("## Local Reference, Unrestricted")
  
  mvaLocalRefUnrestrictedPlot <- ggplot2::ggplot() +
    ggplot2::geom_polygon(data = mvaLocalRefUnrestricted_hulls_pquads, alpha = 0.2,
                          mapping = ggplot2::aes(x = DCA1, 
                                                 y = DCA2, 
                                                 fill = NVC.Comm
                                                 )) +
    ggplot2::geom_point(data = mvaLocalRefUnrestricted_quadrats_survey,
                        mapping = ggplot2::aes(Year = Year,
                                               Group = Group,
                                               Quadrat = Quadrat,
                                               x = DCA1,
                                               y = DCA2)) +
    ggplot2::theme_minimal()

  mvaLocalRefUnrestrictedPlot
  
}

```

\newpage
# Appendix

```{r surveyTable, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

if("surveyTable" %in% reportOptions){
  
  cat("\\newpage")
  cat("## Survey Data Table")

  kableExtra::kbl(x = surveyTable, format = "latex", booktabs = TRUE,
                  longtable = TRUE, linesep = "",
                  caption = "Survey Data Table") |>
    kableExtra::kable_styling(latex_options = c("repeat_header", "HOLD_position"))
  
}

```

